apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: north-pacific.sniffer
  namespace: kube-system
  labels:
    k8s-app: sniffer
spec:
  selector:
    matchLabels:
      name: sniffer
  template:
    metadata:
      labels:
        name: sniffer
    spec:
      hostNetwork: true
      tolerations:
      containers:
      - name: tcpdump
        image: docker.io/cybra/sniffer.north-pacific:0-alpha0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
